# Generated by Django 3.2.5 on 2021-07-21 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_fundacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscripcion',
            name='vigencia',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
