# Generated by Django 3.2.5 on 2021-07-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_tipomascota_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='actualizacion',
            field=models.DateTimeField(null=True),
        ),
    ]
