# Generated by Django 3.2.5 on 2021-07-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_carroproducto_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carroproducto',
            old_name='precio_descuento',
            new_name='precio',
        ),
    ]
