# Generated by Django 3.2.5 on 2021-07-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_precio_descuento_carroproducto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carroproducto',
            name='precio',
            field=models.IntegerField(blank=True),
        ),
    ]
