# Generated by Django 3.2.5 on 2021-07-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_carroproducto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='comentario',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
