# Generated by Django 3.2.5 on 2021-07-24 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
