# Generated by Django 3.2.5 on 2021-07-24 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_despacho_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carro'),
        ),
    ]
