# Generated by Django 3.2.5 on 2021-07-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_despacho_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='carro',
        ),
        migrations.AddField(
            model_name='despacho',
            name='venta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.venta'),
        ),
        migrations.AlterField(
            model_name='estadodespacho',
            name='nombre',
            field=models.CharField(default='Preparando', max_length=500),
        ),
    ]
